meta:
  id: gmp_433_beacon
  endian: le
  bit_endian: le
doc: |
  Ghost Meshnet Protocol (GMP) - 433MHz Control Plane Beacon.
  © 2026 Tiny Innovations Group Ltd. All Rights Reserved.
  Strictly 104 bytes. Carries node discovery, X3DH handshake state, and
  RTS/CTS air-traffic coordination for the 868MHz Data Plane.

seq:
  # ---------------------------------------------------------------------------
  # 32-bit (4-byte) Unified Header
  # ---------------------------------------------------------------------------
  - id: control_type
    type: b4
    enum: control_type_enum
  - id: power_state
    type: b4
    enum: power_state_enum
  - id: epoch_minutes
    type: b24
    doc: 'Minutes since Jan 1, 2024. Prevents long-term replay attacks.'

  # ---------------------------------------------------------------------------
  # Cryptographic Payload (100 bytes)
  # ---------------------------------------------------------------------------
  - id: sender_node_id
    type: u4
  - id: public_identity_key
    size: 32
    doc: 'Curve25519 Public Key for X3DH initialisation.'
  - id: hardware_signature
    size: 64
    doc: 'Ed25519 signature generated by hardware PUF or Secure Enclave.'

enums:
  control_type_enum:
    0b0000: discovery_beacon
    0b0001: x3dh_handshake_init
    0b0010: x3dh_handshake_response
    0b0011: rts_request_to_send
    0b0100: cts_clear_to_send
    # 0b0101 .. 0b1111 reserved for future protocol expansion.

  power_state_enum:
    0b0000: critical_do_not_route
    0b0001: battery_7_percent
    0b0010: battery_14_percent
    0b0011: battery_21_percent
    0b0100: battery_28_percent
    0b0101: battery_35_percent
    0b0110: battery_42_percent
    0b0111: battery_50_percent
    0b1000: battery_57_percent
    0b1001: battery_64_percent
    0b1010: battery_71_percent
    0b1011: battery_78_percent
    0b1100: battery_85_percent
    0b1101: battery_92_percent
    0b1110: battery_100_percent
    0b1111: external_solar_prioritize

instances:
  is_hardware_aligned:
    value: _io.size == 104
    doc: 'Strict validation: enforces 32-bit / 64-bit memory alignment.'
